//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_TCD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gerente
    {
        public Gerente()
        {
            this.Vendas = new HashSet<Vendas>();
        }
    
        public int idGerente { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Formacao { get; set; }
        public string Departamento { get; set; }
        public string Sala { get; set; }
        public int Login { get; set; }
        public int Senha { get; set; }
    
        public virtual ICollection<Vendas> Vendas { get; set; }
    }
}
