//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_TCD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maquina
    {
        public Maquina()
        {
            this.Vendas = new HashSet<Vendas>();
        }
    
        public int idMaquina { get; set; }
        public int idMarca { get; set; }
        public string Nome { get; set; }
        public string Modelo { get; set; }
        public int AnoFabricacao { get; set; }
        public string Motor { get; set; }
        public string Potencia { get; set; }
        public string Combustivel { get; set; }
        public int PesoMaquina { get; set; }
        public string Cor { get; set; }
        public decimal ValorMaquina { get; set; }
        public string Status { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual ICollection<Vendas> Vendas { get; set; }
    }
}
