//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_TCD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        public Marca()
        {
            this.Maquina = new HashSet<Maquina>();
        }
    
        public int idMarca { get; set; }
        public string Nome { get; set; }
        public string NomeOriginal { get; set; }
        public string Industira { get; set; }
        public int AnoFundacao { get; set; }
        public string Fundador { get; set; }
        public string Presidente_CEO { get; set; }
        public string Sede { get; set; }
        public string Tipo { get; set; }
        public string Site { get; set; }
        public string Produtos { get; set; }
    
        public virtual ICollection<Maquina> Maquina { get; set; }
    }
}
