//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_TCD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseBancosEntities1 : DbContext
    {
        public DatabaseBancosEntities1()
            : base("name=DatabaseBancosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Gerente> Gerente { get; set; }
        public DbSet<Maquina> Maquina { get; set; }
        public DbSet<Marca> Marca { get; set; }
        public DbSet<Transportadora> Transportadora { get; set; }
        public DbSet<Vendas> Vendas { get; set; }
        public DbSet<Vendedor> Vendedor { get; set; }
    }
}
