//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_TCD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportadora
    {
        public Transportadora()
        {
            this.Vendas = new HashSet<Vendas>();
        }
    
        public int idTransportadora { get; set; }
        public string Nome { get; set; }
        public string CidadeSede { get; set; }
        public string Frota { get; set; }
        public string CidadesFiliais { get; set; }
        public string Fone { get; set; }
        public string Email { get; set; }
        public decimal ValorFrete { get; set; }
        public string TempoEntrega { get; set; }
    
        public virtual ICollection<Vendas> Vendas { get; set; }
    }
}
