//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_TCD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendas
    {
        public int idVenda { get; set; }
        public int idCliente { get; set; }
        public Nullable<int> idGerente { get; set; }
        public Nullable<int> idVendedor { get; set; }
        public int idMaquina { get; set; }
        public int idTransportadora { get; set; }
        public System.DateTime DataVenda { get; set; }
        public decimal FreteTotal { get; set; }
        public decimal CustoTotal { get; set; }
        public string EstadoCompra { get; set; }
        public string CidadeCompra { get; set; }
        public int QtProdutos { get; set; }
        public string CidadeDestino { get; set; }
        public string EstadoDestino { get; set; }
        public Nullable<decimal> DescontoVenda { get; set; }
        public string EnderecoEntrega { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Gerente Gerente { get; set; }
        public virtual Maquina Maquina { get; set; }
        public virtual Transportadora Transportadora { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
